### ISSUE TITLE
Patter matching arrays problem

### ISSUE THREAD

**Issue by ivanxuu** [versilov/matrex#19]
I think this code summarizes my problem:

```elixir
iex(1)> [a|b]= [1,2]
[1, 2]
iex(2)> a
1
iex(3)> b
[2]
```
Note that `b` is between brackets because is a list.

```elixir
iex(4)> [a|b] = [Matrex.new([[1]])|Matrex.new([[2]])]
[#Matrex[1×1]
┌         ┐
│     1.0 │
└         ┘ |
 #Matrex[1×1]
┌         ┐
│     2.0 │
└         ┘]
iex(5)> a
#Matrex[1×1]
┌         ┐
│     1.0 │
└         ┘
iex(6)> b
#Matrex[1×1]
┌         ┐
│     2.0 │
└         ┘
```
### PROBLEM:

I was expecting `b` to be a list, and equal to:

``` elixir
iex(6)> b
[#Matrex[1×1]
┌         ┐
│     2.0 │
└         ┘]
```
(Note the extra brackets.)

**Comment by OvermindDL1** [comment]
A %Matrix struct is a struct, so it's like doing `[1 | 2]`, the tail isn't a list, it's a struct, and all you are doing is matching out the struct from the tail.  This is all normal Elixir and nothing to do with Matrex at all.  :-)

I.E.  If you had your Matrex example match your integer example by having `[Matrex.new([[1]]), Matrex.new([[2]])]` instead of `[Matrex.new([[1]]) | Matrex.new([[2]])]`, then it would work as you expect.

Different tests should always match, otherwise different output should be expected.

**Comment by ivanxuu** [comment]
Yep, you are completely right. I probably needed some more coffee. Thanks

**Comment by OvermindDL1** [comment]
Might be good to close this issue, I can't as I'm not the dev or the author.  ^.^
