### ISSUE TITLE
Do not use :io.columns on inspect

### ISSUE THREAD

**Issue by josevalim** [versilov/matrex#2]
`inspect` can be used in multiple occasions, not only the terminal, so it is best to not rely on `:io.columns` and instead use the `width` option given to `opts`. So instead of:

```elixir
    def inspect(%Matrex{} = matrex, opts) do
      {:ok, columns} = :io.columns()
      Matrex.Inspect.do_inspect(matrex, columns, 21)
    end
```

One should do:

```elixir
    def inspect(%Matrex{} = matrex, opts) do
      columns = opts.width
      Matrex.Inspect.do_inspect(matrex, columns, 21)
    end
```

Notice that `width` may be infinity. In this case you may want to handle that by setting a default value, such as 80 or whatever.

PS: note there is a Matrix.Inspect.inspect function but that is exactly the same as calling `IO.inspect(matrex)`. :)

**Comment by versilov** [comment]
Thanks, fixed.

The idea behind `:io.columns()` was to use screen space to the maximum. 
Previous version of `inspect/2` used `opts.width`, but it turned out it was always 80, no matter what the actual width of the terminal was.

So, no we have a `print/2` for that.

If I got you correctly, `width` can be `:infinity` atom. Got that covered, although could not find such value in the docs.

PS: `Matrex.Inspect.inspect/2` removed.
